// <auto-generated />
namespace _06数据库迁移之Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Donator_Add_CreationTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Donator_Add_CreationTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201607150953215_Donator_Add_CreationTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
